[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.98"
license = "AGPL-3.0-only"
repository = "https://github.com/(a definir)/sigtap-aberto"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.release]
lto = "thin"
codegen-units = 4
strip = true
