export const UFS = [
  { id: "AC", rotulo: "Acre (AC)" },
  { id: "AL", rotulo: "Alagoas (AL)" },
  { id: "AP", rotulo: "Amapá (AP)" },
  { id: "AM", rotulo: "Amazonas (AM)" },
  { id: "BA", rotulo: "Bahia (BA)" },
  { id: "CE", rotulo: "Ceará (CE)" },
  { id: "DF", rotulo: "Distrito Federal (DF)" },
  { id: "ES", rotulo: "Espírito Santo (ES)" },
  { id: "GO", rotulo: "Goiás (GO)" },
  { id: "MA", rotulo: "Maranhão (MA)" },
  { id: "MT", rotulo: "Mato Grosso (MT)" },
  { id: "MS", rotulo: "Mato Grosso do Sul (MS)" },
  { id: "MG", rotulo: "Minas Gerais (MG)" },
  { id: "PA", rotulo: "Pará (PA)" },
  { id: "PB", rotulo: "Paraíba (PB)" },
  { id: "PR", rotulo: "Paraná (PR)" },
  { id: "PE", rotulo: "Pernambuco (PE)" },
  { id: "PI", rotulo: "Piauí (PI)" },
  { id: "RJ", rotulo: "Rio de Janeiro (RJ)" },
  { id: "RN", rotulo: "Rio Grande do Norte (RN)" },
  { id: "RS", rotulo: "Rio Grande do Sul (RS)" },
  { id: "RO", rotulo: "Rondônia (RO)" },
  { id: "RR", rotulo: "Roraima (RR)" },
  { id: "SC", rotulo: "Santa Catarina (SC)" },
  { id: "SP", rotulo: "São Paulo (SP)" },
  { id: "SE", rotulo: "Sergipe (SE)" },
  { id: "TO", rotulo: "Tocantins (TO)" },
];
